variables:
  IMAGE_NAME: maven:3.8-openjdk-11

stages:
  - test

run_tests:
  stage: test
  image: $IMAGE_NAME
  before_script:
    - apt-get update && apt-get install make
  script:
    - mvn clean verify

  artifacts:
          when: always
          expire_in: 6 mos
          paths:
            - target/site/serenity/*
            - target/failsafe-reports/TEST-*.xml